update

diff --git a/Databases/Redis/Start_up/cluster b/Databases/Redis/Start_up/cluster
--- a/Databases/Redis/Start_up/cluster
+++ b/Databases/Redis/Start_up/cluster
@@ -12,101 +12,99 @@ PASSWD=5by65aSn5peg5q+UcmVkaXM
 # You may want to put the above config parameters into config.sh in order to
 # override the defaults without modifying this script.
 if [ -a config.sh ]; then
-   source "config.sh"
+  source "config.sh"
 fi
 
 # Computed vars
-ENDPORT=$((PORT+NODES))
+ENDPORT=$((PORT + NODES))
 
 if [ "$1" == "start" ]; then
-    while [ $((PORT < ENDPORT)) != "0" ]; do
-        PORT=$((PORT+1))
-        echo "Starting $PORT"
-        redis-server --port $PORT  \
-        --protected-mode $PROTECTED_MODE \
-        --cluster-enabled yes \
-        --cluster-config-file nodes-${PORT}.conf \
-        --cluster-node-timeout $TIMEOUT \
-        --appendonly yes \
-        --appendfilename appendonly-${PORT}.aof \
-        --dbfilename dump-${PORT}.rdb \
-        --logfile ${PORT}.log \
-        --aof-use-rdb-preamble yes \
-        --daemonize yes  \
-        --requirepass $PASSWD \
-        --${ADDITIONAL_OPTIONS}
-    done
-    exit 0
+  while [ $((PORT < ENDPORT)) != "0" ]; do
+    PORT=$((PORT + 1))
+    echo "Starting $PORT"
+    redis-server --port $PORT \
+      --protected-mode $PROTECTED_MODE \
+      --cluster-enabled yes \
+      --cluster-config-file nodes-${PORT}.conf \
+      --cluster-node-timeout $TIMEOUT \
+      --appendonly yes \
+      --appendfilename appendonly-${PORT}.aof \
+      --dbfilename dump-${PORT}.rdb \
+      --logfile ${PORT}.log \
+      --aof-use-rdb-preamble yes \
+      --daemonize yes \
+      --requirepass $PASSWD \
+      --${ADDITIONAL_OPTIONS}
+  done
+  exit 0
 fi
 
 if [ "$1" == "create" ]; then
-    HOSTS=""
-    CLUSTER_HOST=$(curl http://checkip.amazonaws.com/ && [ $? -ne 0 ] && echo "ERROR: The network is not smooth" && exit 1;)
-    while [ $((PORT < ENDPORT)) != "0" ]; do
-        PORT=$((PORT+1))
-        HOSTS="$HOSTS $CLUSTER_HOST:$PORT"
-    done
-    OPT_ARG=""
-    if [ "$2" == "-f" ]; then
-        OPT_ARG="--cluster-yes"
-    fi
-    redis-cli --cluster create $HOSTS -a $PASSWD --cluster-replicas $REPLICAS $OPT_ARG
-    exit 0
+  HOSTS=""
+  CLUSTER_HOST=$(curl http://checkip.amazonaws.com/ && [ $? -ne 0 ] && echo "ERROR: The network is not smooth" && exit 1)
+  while [ $((PORT < ENDPORT)) != "0" ]; do
+    PORT=$((PORT + 1))
+    HOSTS="$HOSTS $CLUSTER_HOST:$PORT"
+  done
+  OPT_ARG=""
+  if [ "$2" == "-f" ]; then
+    OPT_ARG="--cluster-yes"
+  fi
+  redis-cli --cluster create $HOSTS -a $PASSWD --cluster-replicas $REPLICAS $OPT_ARG
+  exit 0
 fi
 
-if [ "$1" == "stop" ]
-then
-    while [ $((PORT < ENDPORT)) != "0" ]; do
-        PORT=$((PORT+1))
-        echo "Stopping $PORT"
-        redis-cli -p $PORT -a $PASSWD shutdown nosave
-    done
-    exit 0
+if [ "$1" == "stop" ]; then
+  while [ $((PORT < ENDPORT)) != "0" ]; do
+    PORT=$((PORT + 1))
+    echo "Stopping $PORT"
+    redis-cli -p $PORT -a $PASSWD shutdown nosave
+  done
+  exit 0
 fi
 
-if [ "$1" == "watch" ]
-then
-    PORT=$((PORT+1))
-    while [ 1 ]; do
-        clear
-        date
-        redis-cli -p $PORT  -a $PASSWD cluster nodes  | head -30
-        sleep 3
-    done
-    exit 0
+if [ "$1" == "watch" ]; then
+  PORT=$((PORT + 1))
+  while [ 1 ]; do
+    clear
+    date
+    redis-cli -p $PORT -a $PASSWD cluster nodes | head -30
+    sleep 3
+  done
+  exit 0
 fi
 
 if [ "$1" == "tail" ]; then
-    INSTANCE=$2
-    PORT=$((PORT+INSTANCE))
-    tail -f ${PORT}.log
-    exit 0
+  INSTANCE=$2
+  PORT=$((PORT + INSTANCE))
+  tail -f ${PORT}.log
+  exit 0
 fi
 
 if [ "$1" == "tailall" ]; then
-    tail -f *.log
-    exit 0
+  tail -f *.log
+  exit 0
 fi
 
 if [ "$1" == "call" ]; then
-    while [ $((PORT < ENDPORT)) != "0" ]; do
-        PORT=$((PORT+1))
-        redis-cli -p $PORT $2 $3 $4 $5 $6 $7 $8 $9 -a $PASSWD
-    done
-    exit 0
+  while [ $((PORT < ENDPORT)) != "0" ]; do
+    PORT=$((PORT + 1))
+    redis-cli -p $PORT $2 $3 $4 $5 $6 $7 $8 $9 -a $PASSWD
+  done
+  exit 0
 fi
 
 if [ "$1" == "clean" ]; then
-    rm -rf *.log
-    rm -rf appendonly*.aof
-    rm -rf dump*.rdb
-    rm -rf nodes*.conf
-    exit 0
+  rm -rf *.log
+  rm -rf appendonly*.aof
+  rm -rf dump*.rdb
+  rm -rf nodes*.conf
+  exit 0
 fi
 
 if [ "$1" == "clean-logs" ]; then
-    rm -rf *.log
-    exit 0
+  rm -rf *.log
+  exit 0
 fi
 
 echo "Usage:      [start|create|stop|watch|tail|clean|call]"
